version: "3"
services:
  app:
    image: chess-app
    depends_on:
      - db
    ports:
      - "8080:8889"
    environment:
      POSTGRES_HOST: db
      APP_HOST_PORT: 8080

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chess
    ports:
      - "3030:5432"