version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: chess