export enum ProfileActionTypeEnum {
  PROFILE_REQUEST_STARTED = 'PROFILE_REQUEST_STARTED',
  PROFILE_REQUEST_SUCCEED = 'PROFILE_REQUEST_SUCCEED',
  PROFILE_REQUEST_FAILED = 'PROFILE_REQUEST_FAILED',
  PROFILE_SET_USER = 'PROFILE_SET_USER',
  PROFILE_CLEAR_USER = 'PROFILE_CLEAR_USER',
  PROFILE_SET_TOKEN = 'PROFILE_SET_TOKEN',
}
